// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNW9diCDR_QV1Owmc84l1I-7zbKhdljtE',
    appId: '1:588239505190:web:9ff00cf9ee520051bd63e7',
    messagingSenderId: '588239505190',
    projectId: 'final-project-2023-93a29',
    authDomain: 'final-project-2023-93a29.firebaseapp.com',
    storageBucket: 'final-project-2023-93a29.appspot.com',
    measurementId: 'G-E6TVB8CYRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuS4xkgiJkau4hj1WAjVCAa6ZKQv3kjT8',
    appId: '1:588239505190:android:e77371a28ae09671bd63e7',
    messagingSenderId: '588239505190',
    projectId: 'final-project-2023-93a29',
    storageBucket: 'final-project-2023-93a29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN0bpgDhMET_mOknJkx59ENEbzjMoc8kY',
    appId: '1:588239505190:ios:4e6c9d8ffd1afdd7bd63e7',
    messagingSenderId: '588239505190',
    projectId: 'final-project-2023-93a29',
    storageBucket: 'final-project-2023-93a29.appspot.com',
    iosClientId: '588239505190-0eu8srbt8mo8072aedo6g9kjkk6g5evg.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN0bpgDhMET_mOknJkx59ENEbzjMoc8kY',
    appId: '1:588239505190:ios:4e6c9d8ffd1afdd7bd63e7',
    messagingSenderId: '588239505190',
    projectId: 'final-project-2023-93a29',
    storageBucket: 'final-project-2023-93a29.appspot.com',
    iosClientId: '588239505190-0eu8srbt8mo8072aedo6g9kjkk6g5evg.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject2023',
  );
}
